// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqlahhqkuzlibuqbuhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbGFoaHFrdXpsaWJ1cWJ1aGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDUzMDIsImV4cCI6MjA2NDQyMTMwMn0.2wquPkSgYxgQyzDCgWZ6LOp1BkjHmf-npX_ZdymmrlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);